name: nested-routes
version: 9.0.0
synopsis: Declarative, compositional Wai responses
description: Please see the README on Github at <https://git.localcooking.com/tooling/pred-trie#readme>
maintainer: Athan Clark <athan.clark@gmail.com>
license: BSD3
github: athanclark/nested-routes
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - attoparsec
  - errors
  - exceptions
  - extractable-singleton
  - hashable
  - monad-control-aligned
  - mtl
  - poly-arity >= 0.0.7
  - pred-trie >= 0.6.0
  - regex-compat
  - text
  - tries >= 0.0.5
  - unordered-containers
  - wai-transformers >= 0.0.7
  - wai-middleware-content-type >= 0.6.0
  - wai-middleware-verbs >= 0.3.2

library:
  source-dirs: src

tests:
  spec:
    ghc-options:
      - -threaded
      - -rtsopts
      - -Wall
      - -with-rtsopts=-N
    main: Test.hs
    source-dirs:
      - test
    dependencies:
      - base
      - nested-routes
      - http-types
      - hspec
      - hspec-wai
      - tasty
      - tasty-hspec
