name: nested-routes
version: 10.0.0
synopsis: Declarative, compositional Wai responses
description: Please see the README on Github at <https://github.com/athanclark/nested-routes#readme>
maintainer: Athan Clark <athan.clark@gmail.com>
license: BSD3
github: athanclark/nested-routes
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.11 && < 5
  - attoparsec
  - errors
  - exceptions
  - extractable-singleton
  - hashable
  - monad-control-aligned >= 0.0.2
  - mtl
  - poly-arity >= 0.0.7
  - pred-trie >= 0.6.1
  - regex-compat
  - text
  - tries >= 0.0.6
  - unordered-containers
  - wai >= 3.2.1
  - wai-transformers >= 0.1.0
  - wai-middleware-content-type >= 0.7.0
  - wai-middleware-verbs >= 0.4.0.1

library:
  source-dirs: src

tests:
  spec:
    ghc-options:
      - -threaded
      - -rtsopts
      - -Wall
      - -with-rtsopts=-N
    main: Test.hs
    source-dirs:
      - test
    dependencies:
      - base
      - nested-routes
      - http-types
      - hspec
      - hspec-wai
      - tasty
      - tasty-hspec
