name: nested-routes
version: 8.2.0
synopsis: Declarative, compositional Wai responses
description:
  This library attempts to make it easier to write nice Wai response handlers
  by giving us a Sinatra/
  <https://hackage.haskell.org/package/scotty Scotty>-like syntax for declaring HTTP-verb oriented
  routes, in addition to file-extension handling and rose-tree like composition.
  Not only do we have literal route specification, like
  <https://hackage.haskell.org/package/scotty Scotty> &
  <https://hackage.haskell.org/package/spock Spock>, but we
  can also embed
  <https://hackage.haskell.org/package/attoparsec Attoparsec>
  parsers and <https://hackage.haskell.org/package/regex-compat Regular Expressions>
  /directly/ in our routes, with our handlers
  reflecting their results.
maintainer: Athan Clark <athan.clark@gmail.com>
license: BSD3
github: athanclark/nested-routes
category: Web

ghc-options: -Wall

dependencies:
  - base >= 4.9 && < 5
  - attoparsec
  - bifunctors
  - bytestring
  - errors
  - exceptions
  - extractable-singleton
  - hashable
  - hashtables
  - monad-control-aligned
  - mtl
  - poly-arity >= 0.0.7
  - pred-set >= 0.0.1
  - pred-trie >= 0.5.1
  - regex-compat
  - semigroups
  - text
  - transformers
  - tries
  - unordered-containers
  - wai-transformers >= 0.0.7
  - wai-middleware-content-type >= 0.5.0.1
  - wai-middleware-verbs >= 0.3.1

library:
  source-dirs: src

tests:
  spec:
    ghc-options:
      - -threaded
      - -rtsopts
      - -Wall
      - -with-rtsopts=-N
    main: Test.hs
    source-dirs:
      - test
    dependencies:
      - base
      - nested-routes
      - http-types
      - hspec
      - hspec-wai
      - tasty
      - tasty-hspec
