flags: {}
packages:
- '.'
- location:
    git: https://github.com/athanclark/wai-middleware-content-type
    commit: 1dca0f455b7727b96c6555572f699baf741cca6e
  extra-dep: true
- location:
    git: https://github.com/athanclark/wai-middleware-verbs
    commit: 7dc4cc25b03158ed15825544ca215eafec7deb14
  extra-dep: true
- location:
    git: https://github.com/athanclark/wai-transformers
    commit: a72b2c061fedf1e131dd0a64da008312003e150b
  extra-dep: true
extra-deps:
  - composition-extra-2.0.0
  - tries-0.0.2
  - rose-trees-0.0.2
  - pred-trie-0.3.0
  - wai-util-0.8
  - http-accept-0.2
  - poly-arity-0.0.7
  - wai-transformers-0.0.4
  - wai-middleware-content-type-0.1.0
  - wai-middleware-verbs-0.1.0
resolver: nightly-2015-11-27
