flags: {}
packages:
- '.'
extra-deps:
  - poly-arity-0.0.6
  - sets-0.0.5
  - wai-util-0.8
  - commutative-0.0.1.4
  - http-accept-0.2
  - composition-extra-2.0.0
  - tries-0.0.2
  - rose-trees-0.0.2
  - pred-trie-0.3.0
resolver: nightly-2015-09-17
