flags: {}
packages:
- '.'
- location:
    git: https://github.com/athanclark/wai-middleware-content-type
    commit: 20e49185abd2dbed6eaf2222e829b91a4de69ff4
  extra-dep: true
- location:
    git: https://github.com/athanclark/wai-middleware-verbs
    commit: 2ee9985619084f02eb4423ca95874f331f6e014b
  extra-dep: true
- location:
    git: https://github.com/athanclark/wai-transformers
    commit: a72b2c061fedf1e131dd0a64da008312003e150b
  extra-dep: true
- location:
    git: https://github.com/athanclark/pred-trie
    commit: f9e0b1b3762bf200d6d3f7b4fd3480b1a62aad83
  extra-dep: true
extra-deps:
  - composition-extra-2.0.0
  - tries-0.0.3
  - rose-trees-0.0.3
  - pred-trie-0.4.0
  - wai-util-0.8
  - http-accept-0.2
  - poly-arity-0.0.7
  - wai-transformers-0.0.4
  - wai-middleware-verbs-0.1.1
resolver: nightly-2015-12-10
