flags: {}
packages:
- '.'
- '../pred-trie'
- '../wai-transformers'
- '../wai-middleware-verbs'
- location:
    git: https://github.com/athanclark/wai-middleware-content-type
    commit: f7f00f799d83919b2945801c46e48bbc9c47be90
  extra-dep: true
extra-deps:
  - composition-extra-2.0.0
  - tries-0.0.4
  - rose-trees-0.0.3
  - wai-util-0.8
  - http-accept-0.2
  - poly-arity-0.0.7
  - wai-transformers-0.0.4
  - wai-middleware-verbs-0.2.0
  - wai-middleware-content-type-0.4.0
  - pred-trie-0.5.1
  - pred-set-0.0.1
  - HSet-0.0.0
resolver: nightly-2016-04-15
