flags: {}
packages:
- '.'
- location:
    git: https://github.com/athanclark/wai-middleware-content-type
    commit: 3ef187df2f3677969623fc8ab678bef6eb89c314
  extra-dep: true
extra-deps:
  - composition-extra-2.0.0
  - tries-0.0.4
  - rose-trees-0.0.3
  - pred-trie-0.5.0
  - wai-util-0.8
  - http-accept-0.2
  - poly-arity-0.0.7
  - wai-transformers-0.0.4
  - wai-middleware-verbs-0.2.0
  - wai-middleware-content-type-0.3.0
resolver: nightly-2016-01-19
